# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=bow_of_lost_souls
model.bow_pulling_0=bow_of_lost_souls_pulling_0
model.bow_pulling_1=bow_of_lost_souls_pulling_1
model.bow_pulling_2=bow_of_lost_souls_pulling_2
# components.custom_name=iregex:(Bow of Lost Souls)
components.custom_model_data=10
