# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=bubble_bow
model.bow_pulling_0=bubble_bow_pulling_0
model.bow_pulling_1=bubble_bow_pulling_1
model.bow_pulling_2=bubble_bow_pulling_2
# components.custom_name=iregex:(Bubble Bow)
components.custom_model_data=11
