# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=call_of_the_void
model.bow_pulling_0=call_of_the_void_pulling_0
model.bow_pulling_1=call_of_the_void_pulling_1
model.bow_pulling_2=call_of_the_void_pulling_2
# components.custom_name=iregex:(Call of the Void)
components.custom_model_data=14
