# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=ender_dragon_bow
model.bow_pulling_0=ender_dragon_bow_pulling_0
model.bow_pulling_1=ender_dragon_bow_pulling_1
model.bow_pulling_2=ender_dragon_bow_pulling_2
# components.custom_name=iregex:(Ender Dragon Bow)
components.custom_model_data=22
