# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=hunters_promise
model.bow_pulling_0=hunters_promise_pulling_0
model.bow_pulling_1=hunters_promise_pulling_1
model.bow_pulling_2=hunters_promise_pulling_2
# components.custom_name=iregex:(Hunter's Promise)
components.custom_model_data=27
