# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=leeching_thief
model.bow_pulling_0=leeching_thief_pulling_0
model.bow_pulling_1=leeching_thief_pulling_1
model.bow_pulling_2=leeching_thief_pulling_2
# components.custom_name=iregex:(Leeching Thief)
components.custom_model_data=29
