# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=petra_bow_power
model.bow_pulling_0=petra_bow_power_pulling_0
model.bow_pulling_1=petra_bow_power_pulling_1
model.bow_pulling_2=petra_bow_power_pulling_2
# components.custom_name=iregex:(Petra's Bow)
enchantments=power
enchantmentLevels:5-255
weight=1
components.custom_model_data=38
