# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=./slingshot
model.bow_pulling_0=./slingshot_pulling_0
model.bow_pulling_1=./slingshot_pulling_1
model.bow_pulling_2=./slingshot_pulling_2
# components.custom_name=iregex:(Slingshot)
components.custom_model_data=54
