# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=space_arm_cannon
model.bow_pulling_0=space_arm_cannon_pulling_0
model.bow_pulling_1=space_arm_cannon_pulling_1
model.bow_pulling_2=space_arm_cannon_pulling_2
# components.custom_name=iregex:(Space Arm Cannon)
components.custom_model_data=57
