# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:bow
model=the_green_menace
model.bow_pulling_0=the_green_menace_pulling_0
model.bow_pulling_1=the_green_menace_pulling_1
model.bow_pulling_2=the_green_menace_pulling_2
# components.custom_name=iregex:(The Green Menace)
components.custom_model_data=61
