# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=1
nbt.1.ArmorItems.3.id=minecraft:grass_block

skins.2=2
nbt.2.ArmorItems.3.id=minecraft:oak_leaves

skins.3=3
nbt.3.ArmorItems.3.id=minecraft:white_wool