# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=1 9
biomes.1=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean
weights.1=1 8

skins.2=3 9
biomes.2=mangrove_swamp savanna savanna_plateau windswept_savanna dark_forest
weights.2=1 8

skins.3=4 9
biomes.3=windswept_hills windswept_gravelly_hills windswept_forest stony_peaks
weights.3=1 8

skins.4=5 9
biomes.4=meadow birch_forest old_growth_birch_forest beach cherry_grove
weights.4=1 8

skins.5=6 9
biomes.5=jungle sparse_jungle bamboo_jungle flower_forest
weights.5=1 8

skins.6=7 9
biomes.6=desert badlands eroded_badlands wooded_badlands
weights.6=1 8

skins.7=8 9
biomes.7=stony_shore warm_ocean lukewarm_ocean deep_lukewarm_ocean ocean cold_ocean deep_cold_ocean deep_ocean mushroom_fields
weights.7=1 8

skins.8=2 9
weights.8=1 8