# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=2
heights.1=(-1)-(-64)

skins.2=3
heights.2=60-80
biomes.2=old_growth_pine_taiga old_growth_spruce_taiga

skins.3=1