# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=4
biomes.1=jungle sparse_jungle bamboo_jungle

skins.2=1
biomes.2=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean

skins.3=2
biomes.3=old_growth_pine_taiga old_growth_spruce_taiga taiga

skins.4=3