# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=3 9 11
biomes.1=desert
weights.1=32 32 1

skins.2=5 11
biomes.2=savanna savanna_plateau windswept_savanna badlands eroded_badlands wooded_badlands
weights.2=64 1

skins.3=6 10-11
biomes.3=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean
weights.3=32 32 1

skins.4=7 11
biomes.4=swamp mangrove_swamp
weights.4=64 1

skins.5=8 11
biomes.5=old_growth_pine_taiga old_growth_spruce_taiga taiga
weights.5=64 1

skins.6=4 11
biomes.6=jungle sparse_jungle bamboo_jungle
weights.6=64 1

skins.7=1-2 11
weights.7=32 32 1