# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=1-3
biomes.1=desert savanna_plateau savanna windswept_savanna badlands jungle sparse_jungle bamboo_jungle eroded_badlands wooded_badlands warm_ocean
weights.1=32 160 1

skins.2=1-3
weights.2=160 32 1