# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=coal_ore
method=random
tiles=textures/block/coal_ore coal_ore_1
weights=6 3
heights=(-64)-47 49-320
biomes=dripstone_caves