# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=deepslate_iron_ore
method=random
tiles=textures/block/deepslate_iron_ore deepslate_iron_ore_1
weights=6 3