# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=deepslate_coal_ore
method=random
tiles=textures/block/deepslate_coal_ore deepslate_coal_ore_1
weights=6 3