# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=1
name.1=iregex:(Witch 1)

models.2=2
name.2=iregex:(Witch 2)

models.3=3
name.3=iregex:(Witch 3)

models.4=4
name.4=iregex:(Witch 4)

models.5=5
name.5=iregex:(Witch 5)

models.6=6
name.6=iregex:(Witch 6)

models.7=7
name.7=iregex:(Witch 7)