# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=sand
method=random
tiles=textures/block/sand 0-4
biomes=warm_ocean lukewarm_ocean deep_lukewarm_ocean ocean deep_ocean cold_ocean deep_cold_ocean
weights=1024 4 4 4 1 1
maxHeight=80
faces=top
weight=1