# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=sand
method=random
tiles=textures/block/sand 0-4
biomes=river beach stony_shore frozen_ocean deep_frozen_ocean
weights=4096 8 8 8 1 1
maxHeight=80
minHeight=48
faces=top
weight=1