# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
model=./broken_ominous_elytra
matchItems=elytra
# components.custom_name=iregex:(Ominous Elytra)
components.damage=431
weight=1
components.custom_model_data=60
