# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=dirt podzol rooted_dirt coarse_dirt
method=overlay
tiles=<skip> <skip> <skip> <skip> <skip> <skip> <skip> 7 <skip> 9 <skip> <skip> <skip> <skip> <skip> <skip> <skip>
connect=block
connectTiles=grass_block_side
faces=sides
tintIndex=1
tintBlock=minecraft:grass_block
weight=3