# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=netherrack
connectBlocks=warped_wart_block
connect=block
method=overlay
tiles=<skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> netherrack_overlay <skip>
biomes=warped_forest