# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=cracked_polished_blackstone_bricks
method=random
tiles=textures/block/cracked_polished_blackstone_bricks cracked_polished_blackstone_bricks_1 basalt_cracked_polished_blackstone_bricks
biomes=basalt_deltas
weights=18 1 1