# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=cracked_polished_blackstone_bricks
method=random
tiles=textures/block/cracked_polished_blackstone_bricks.png cracked_polished_blackstone_bricks_1.png
weights=19 1