# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=polished_blackstone_bricks
method=random
tiles=textures/block/polished_blackstone_bricks crimson_polished_blackstone_bricks_0 crimson_polished_blackstone_bricks_1 crimson_polished_blackstone_bricks_2
biomes=crimson_forest
weights=7 1 1 1
symmetry=all