# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=1
name.1=iregex:(Skeleton 1)

models.2=2
name.2=iregex:(Skeleton 2)

models.3=3
name.3=iregex:(Skeleton 3)

models.4=4
name.4=iregex:(Skeleton 4)

models.5=5
name.5=iregex:(Skeleton 5)