# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=sandstone
faces=sides
method=ctm_compact
tiles=textures/block/sandstone.png textures/block/sandstone_bottom.png textures/block/sandstone_bottom.png textures/block/sandstone.png 4