# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=overlay
matchTiles=textures/block/better_grass_side.png textures/block/better_mycelium_side.png textures/block/better_podzol_side.png
faces=sides
tiles=0-16
connectTiles=textures/block/dirt.png textures/block/coarse_dirt.png textures/block/coarse_dirt_0.png textures/block/rooted_dirt.png
tiles=0 0 0 0 0 0 0 7 0 9 0 0 0 0 0 0 0