# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=acacia_log_vertical
method=horizontal
tiles=0 textures/block/acacia_log.png 2 textures/block/acacia_log_vertical.png