# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=minecraft:podzol
method=overlay
tiles=0-16
connect=block
connectTiles=grass_block_top
faces=top
weight=2