# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=glow_lichen_sprouts
tiles=./glow_lichen_sprouts.png
biomes=barely_default:creeper_woods
weight=1