# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=warped_wart_block
method=fixed
tiles=warping_wart_block
biomes=warped_forest nether_wastes soul_sand_valley crimson_forest basalt_deltas