# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=2 4 6 8 10 12 14
health.1=0-10%
weights.1=2 1 1 2 2 1 1

skins.2=1 3 5 7 9 11 13
weights.2=2 1 1 2 2 1 1