# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=dark_oak_log_vertical
method=horizontal
tiles=0 textures/block/dark_oak_log.png 2 textures/block/dark_oak_log_vertical.png