# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:netherite_sword
model=obsidian_broadsword
texture=dark_masters_sword_sharpness
# components.custom_name=iregex:(Dark Master's Sword)
enchantments=sharpness bane_of_arthropods smite
enchantmentLevels:5-255
weight=2
components.custom_model_data=34
