# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:netherite_sword
texture=soul_scythe_fire_aspect
model=optifine/cit/item/scythe
# components.custom_name=iregex:(Soul Scythe)
enchantments=fire_aspect
enchantmentLevels:1-255
weight=2
components.custom_model_data=130
