# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:netherite_sword
model=./thorned_heart
texture=./thorned_heart
# components.custom_name=iregex:(Thorned Heart)
weight=0
components.custom_model_data=150
