# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:netherite_sword
model=optifine/cit/item/anchor
texture=./wrench_fire_aspect
# components.custom_name=ipattern:*Wrench
enchantments=fire_aspect
enchantmentLevels:1-255
weight=1
components.custom_model_data=161
