# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=jungle_log_horizontal
method=horizontal
tiles=0 textures/block/jungle_log.png 2 textures/block/jungle_log_horizontal.png