# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=2
biomes.1=plains sunflower_plains

skins.2=3
biomes.2=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean

skins.3=3
biomes.3=windswept_hills windswept_gravelly_hills windswept_forest meadow stony_peaks
minHeight.3=97

skins.4=4
biomes.4=savanna savanna_plateau windswept_savanna mangrove_swamp jungle desert badlands eroded_badlands wooded_badlands swamp mangrove_swamp

skins.5=1