# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/custom_guis.properties
container=villager
texture=villager_apprentice
professions=armorer:2, butcher:2, cartographer:2, cleric:2, farmer:2, fisherman:2, fletcher:2, leatherworker:2, librarian:2, mason:2, nitwit:2, shepherd:2, toolsmith:2, weaponsmith:2