# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/custom_guis.properties
container=villager
texture=villager_journeyman
professions=armorer:3, butcher:3, cartographer:3, cleric:3, farmer:3, fisherman:3, fletcher:3, leatherworker:3, librarian:3, mason:3, nitwit:3, shepherd:3, toolsmith:3, weaponsmith:3