# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/custom_guis.properties
container=villager
texture=villager_expert
professions=armorer:4, butcher:4, cartographer:4, cleric:4, farmer:4, fisherman:4, fletcher:4, leatherworker:4, librarian:4, mason:4, nitwit:4, shepherd:4, toolsmith:4, weaponsmith:4