# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/custom_guis.properties
container=villager
texture=villager_master
professions=armorer:5, butcher:5, cartographer:5, cleric:5, farmer:5, fisherman:5, fletcher:5, leatherworker:5, librarian:5, mason:5, nitwit:5, shepherd:5, toolsmith:5, weaponsmith:5