# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/custom_guis.properties
container=villager
texture=villager_novice
professions=armorer:1, butcher:1, cartographer:1, cleric:1, farmer:1, fisherman:1, fletcher:1, leatherworker:1, librarian:1, mason:1, nitwit:1, shepherd:1, toolsmith:1, weaponsmith:1