type=item
matchItems=bow
model=./staff_sagrada_winged_staff
model.bow_pulling_0=staff_sagrada_winged_staff_casting
model.bow_pulling_1=staff_sagrada_winged_staff_casting
model.bow_pulling_2=staff_sagrada_winged_staff_casting_charged
# components.custom_name=ipattern:*Aile de Sagrada
components.custom_model_data=85
