type=item
matchItems=bow
model=./staff_holy_celtic_staff
model.bow_pulling_0=staff_holy_celtic_staff_casting
model.bow_pulling_1=staff_holy_celtic_staff_casting
model.bow_pulling_2=staff_holy_celtic_staff_casting_charged
# components.custom_name=ipattern:*Bâton Sacré Celtique
components.custom_model_data=80