type=item
matchItems=bow
model=./staff_golden_crook
model.bow_pulling_0=staff_golden_crook_casting
model.bow_pulling_1=staff_golden_crook_casting
model.bow_pulling_2=staff_golden_crook_casting_charged
# components.custom_name=ipattern:*l'Escroc Doré
components.custom_model_data=79