type=item
matchItems=bow
model=./staff_night
model.bow_pulling_0=staff_night_casting
model.bow_pulling_1=staff_night_casting
model.bow_pulling_2=staff_night_casting_charged
# components.custom_name=ipattern:*Bâton Nocturne
components.custom_model_data=82
