type=item
matchItems=bow
model=./staff_lich_staff
model.bow_pulling_0=staff_lich_staff_casting
model.bow_pulling_1=staff_lich_staff_casting
model.bow_pulling_2=staff_lich_staff_casting_charged
# components.custom_name=ipattern:*Bâton de Liche
components.custom_model_data=81
