type=item
items=bow
model=./staff_basic_wooden_staff
model.bow_pulling_0=staff_basic_wooden_staff_casting
model.bow_pulling_1=staff_basic_wooden_staff_casting
model.bow_pulling_2=staff_basic_wooden_staff_casting_charged
# components.custom_name=ipattern:*Bâton de Bois
components.custom_model_data=74