type=item
matchItems=bow
model=./staff_olwen_staff
model.bow_pulling_0=staff_olwen_staff_casting
model.bow_pulling_1=staff_olwen_staff_casting
model.bow_pulling_2=staff_olwen_staff_casting_charged
# components.custom_name=ipattern:*Bâton d'Olwen
components.custom_model_data=84
