type=item
items=bow
model=./staff_bermundes_hermit_staff
model.bow_pulling_0=staff_bermundes_hermit_staff_casting
model.bow_pulling_1=staff_bermundes_hermit_staff_casting
model.bow_pulling_2=staff_bermundes_hermit_staff_casting_charged
# components.custom_name=ipattern:*Bâton des Bermudes
components.custom_model_data=75