type=item
matchItems=bow
model=./staff_unholy_wisdom
model.bow_pulling_0=staff_unholy_wisdom_casting
model.bow_pulling_1=staff_unholy_wisdom_casting
model.bow_pulling_2=staff_unholy_wisdom_casting_charged
# components.custom_name=ipattern:*Sagesse Impie
components.custom_model_data=86
