type=item
matchItems=bow
model=./staff_northgate_guardian_staff
model.bow_pulling_0=staff_northgate_guardian_staff_casting
model.bow_pulling_1=staff_northgate_guardian_staff_casting
model.bow_pulling_2=staff_northgate_guardian_staff_casting_charged
# components.custom_name=ipattern:*Bâton du Gardien de la Porte
components.custom_model_data=83
