type=item
matchItems=bow
model=./staff_black_snake_staff
model.bow_pulling_0=staff_black_snake_staff_casting
model.bow_pulling_1=staff_black_snake_staff_casting
model.bow_pulling_2=staff_black_snake_staff_casting_charged
# components.custom_name=ipattern:*Bâton Serpent Noir
components.custom_model_data=76
