type=item
matchItems=bow
model=./staff_goblin_witch_staff
model.bow_pulling_0=staff_goblin_witch_staff_casting
model.bow_pulling_1=staff_goblin_witch_staff_casting
model.bow_pulling_2=staff_goblin_witch_staff_casting_charged
# components.custom_name=ipattern:*Bâton de Sorcière Gobeline
components.custom_model_data=78
