type=item
matchItems=bow
model=./staff_divine_staff
model.bow_pulling_0=staff_divine_staff_casting
model.bow_pulling_1=staff_divine_staff_casting
model.bow_pulling_2=staff_divine_staff_casting_charged
# components.custom_name=ipattern:*Bâton Divin
components.custom_model_data=77
