# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=dirt coarse_dirt
method=overlay
tiles=<skip> 1 <skip> 3-13 <skip> 15 <skip>
connect=block
connectBlocks=rooted_dirt
faces=all
innerSeams=true