# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=1
name.1=iregex:(Ravager 1)

models.2=2
name.2=iregex:(Ravager 2)

models.3=3
name.3=iregex:(Ravager 3)

models.4=4
name.4=iregex:(Ravager 4)

models.5=5
name.5=iregex:(Ravager 5)

models.6=6
name.6=iregex:(Ravager 6)

models.7=7
name.7=iregex:(Ravager 7)

models.8=8
name.8=iregex:(Ravager 8)

models.9=9
name.9=iregex:(Ravager 9)

models.10=10
name.10=iregex:(Ravager 10)

models.11=11
name.11=iregex:(Ravager 11)

models.12=12
name.12=iregex:(Ravager 12)

models.13=13
name.13=iregex:(Ravager 13)

models.14=14
name.14=iregex:(Ravager 14)

models.15=15
name.15=iregex:(Ravager 15)

models.16=16
name.16=iregex:(Ravager 16)

models.17=17
name.17=iregex:(Ravager 17)

models.18=18
name.18=iregex:(Ravager 18)