# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=armor
matchItems=netherite_boots
texture.netherite_layer_1=boom_town_layer_1
# components.custom_name=iregex:(boom town boots)
components.custom_model_data=10
