# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=armor
matchItems=netherite_helmet
texture.netherite_layer_1=ellegaard_layer_1
# components.custom_name=iregex:(ellegaard's helmet)
components.custom_model_data=32
