# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=armor
matchItems=netherite_boots
texture.netherite_layer_1=sturdy_shulker_layer_1
# components.custom_name=iregex:(shulker boots)
enchantments=protection fire_protection blast_protection projectile_protection
enchantmentLevels:4-255
weight=1
components.custom_model_data=99
