# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=sandstone_end.png
matchBlocks=minecraft:sandstone
method=ctm_compact
tiles=textures/block/sandstone_end.png textures/block/sandstone_top.png 2-4