# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=1
health.1=75-100%

skins.2=2
health.2=50-74%

skins.3=3
health.3=25-49%

skins.4=4
health.4=2-24%

skins.5=5
health.5=0-1%