# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=2
biomes.1=soul_sand_valley barely_default:the_hollow

skins.2=5
biomes.2=barely_default:nostalgia_hills

skins.3=6
biomes.3=basalt_deltas

skins.4=1 7
biomes.4=crimson_forest

skins.5=1 8
biomes.5=warped_forest

skins.6=1 3-4
biomes.6=lush_caves
weights.6=8 8 1

skins.7=5 25
heights.7=(-1)-(-64)
weights.7=128 1

skins.8=1 9-16
biomes.8=badlands eroded_badlands wooded_badlands
heights.8=320-0

skins.9=1 3 17
biomes.9=swamp
weights.9=64 64 1
minHeight.9=60

skins.10=1 3 23
biomes.10=mangrove_swamp
weights.10=64 64 1
minHeight.10=60

skins.11=1 3 20
biomes.11=jungle sparse_jungle bamboo_jungle
weights.11=64 64 1
heights.11=320-48

skins.12=1 18
weights.12=128 1
biomes.12=snowy_plains old_growth_pine_taiga old_growth_spruce_taiga taiga snowy_taiga windswept_forest grove
minHeight.12=60

skins.13=1 19
weights.13=128 1
biomes.13=birch_forest old_growth_birch_forest
minHeight.13=60

skins.14=1 21
weights.14=128 1
biomes.14=savanna savanna_plateau
minHeight.14=60

skins.15=1 22
weights.15=128 1
biomes.15=dark_forest
minHeight.15=60

skins.16=1 24
weights.16=128 1
biomes.16=cherry_grove
minHeight.16=60

skins.17=1 17
weights.17=128 1
biomes.17=forest flower_forest
minHeight.17=60

skins.18=1 26
weights.18=128 1
biomes.18=pale_garden
minHeight.18=60