# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=bone_block_side
method=random
tiles=textures/block/bone_block_side.png 0 1
biomes=soul_sand_valley
weights=128 1 1
symmetry=all