# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=4 3
health.1=0-10%
biomes.1=savanna savanna_plateau badlands eroded_badlands windswept_savanna wooded_badlands

skins.2=3
biomes.2=savanna savanna_plateau badlands eroded_badlands windswept_savanna wooded_badlands

skins.3=2 1
health.3=0-10%

skins.4=1