# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=ctm_compact
matchTiles=dripstone_block.png
tiles=textures/block/dripstone_single.png textures/block/dripstone_block.png 2-4