# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=wither_rose
tiles=blooming_wither_rose
biomes=nether_wastes crimson_forest warped_forest soul_sand_valley basalt_deltas