# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
model=./oxidized_combat_leggings
matchItems=chainmail_leggings
# components.custom_name=iregex:(combat leggings)
damage=75-100%
components.custom_model_data=3
