# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
model=./weathered_combat_boots
matchItems=chainmail_boots
# components.custom_name=iregex:(combat boots)
damage=50-74%
components.custom_model_data=3
