# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
model=./weathered_trial_leggings
matchItems=chainmail_leggings
# components.custom_name=iregex:(trial leggings)
damage=50-74%
components.custom_model_data=11
