# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=overlay
matchTiles=textures/block/better_mycelium_side.png
faces=sides
tiles=0-16
connectTiles=textures/block/mycelium_side.png
tiles=0 0 0 0 0 0 0 7 0 7 0 0 0 0 0 0 0