# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=warped_nylium
method=fixed
tiles=warping_nylium
biomes=warped_forest nether_wastes soul_sand_valley crimson_forest basalt_deltas