# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./a_bee_crossbow
model.crossbow_pulling_0=./a_bee_crossbow_pulling_0
model.crossbow_pulling_1=./a_bee_crossbow_pulling_1
model.crossbow_pulling_2=./a_bee_crossbow_pulling_2
model.crossbow_arrow=./a_bee_crossbow_arrow
model.crossbow_firework=./a_bee_crossbow_firework
# components.custom_name=iregex:(A Bee Crossbow)
components.custom_model_data=7
