# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./acacia_ballista
model.crossbow_pulling_0=./acacia_ballista_pulling_0
model.crossbow_pulling_1=./acacia_ballista_pulling_1
model.crossbow_pulling_2=./acacia_ballista_pulling_2
model.crossbow_arrow=./acacia_ballista_arrow
model.crossbow_firework=./acacia_ballista_firework
# components.custom_name=iregex:(Acacia Ballista)
components.custom_model_data=1
