# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./arch_crossbow
model.crossbow_pulling_0=./arch_crossbow_pulling_0
model.crossbow_pulling_1=./arch_crossbow_pulling_1
model.crossbow_pulling_2=./arch_crossbow_pulling_2
model.crossbow_arrow=./arch_crossbow_arrow
model.crossbow_firework=./arch_crossbow_firework
# components.custom_name=iregex:(Arch Crossbow)
components.custom_model_data=4
