# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./bamboo_ballista
model.crossbow_pulling_0=./bamboo_ballista_pulling_0
model.crossbow_pulling_1=./bamboo_ballista_pulling_1
model.crossbow_pulling_2=./bamboo_ballista_pulling_2
model.crossbow_arrow=./bamboo_ballista_arrow
model.crossbow_firework=./bamboo_ballista_firework
# components.custom_name=iregex:(Bamboo Ballista)
components.custom_model_data=9
