# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./bat_crossbow
model.crossbow_pulling_0=./bat_crossbow_pulling_0
model.crossbow_pulling_1=./bat_crossbow_pulling_1
model.crossbow_pulling_2=./bat_crossbow_pulling_2
model.crossbow_arrow=./bat_crossbow_arrow
model.crossbow_firework=./bat_crossbow_firework
# components.custom_name=iregex:(Bat Crossbow)
components.custom_model_data=11
