# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./catkin_cannon
model.crossbow_pulling_0=./catkin_cannon_pulling_0
model.crossbow_pulling_1=./catkin_cannon_pulling_1
model.crossbow_pulling_2=./catkin_cannon_pulling_2
model.crossbow_arrow=./catkin_cannon_arrow
model.crossbow_firework=./catkin_cannon_firework
# components.custom_name=iregex:(Catkin Cannon)
components.custom_model_data=15
