# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./caver_crossbow
model.crossbow_pulling_0=./caver_crossbow_pulling_0
model.crossbow_pulling_1=./caver_crossbow_pulling_1
model.crossbow_pulling_2=./caver_crossbow_pulling_2
model.crossbow_arrow=./caver_crossbow_arrow
model.crossbow_firework=./caver_crossbow_firework
# components.custom_name=iregex:(Caver's Crossbow)
damage=0-24%
components.custom_model_data=16
