# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./cave_spider_microshot
model.crossbow_pulling_0=./cave_spider_microshot_pulling_0
model.crossbow_pulling_1=./cave_spider_microshot
model.crossbow_pulling_2=./cave_spider_microshot
model.crossbow_arrow=./cave_spider_microshot_arrow
model.crossbow_firework=./cave_spider_microshot_firework
# components.custom_name=iregex:(Cave Spider Microshot)
components.custom_model_data=17
