# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./cherry_popper
model.crossbow_pulling_0=./cherry_popper_pulling_0
model.crossbow_pulling_1=./cherry_popper_pulling_1
model.crossbow_pulling_2=./cherry_popper_pulling_2
model.crossbow_arrow=./cherry_popper_arrow
model.crossbow_firework=./cherry_popper_firework
# components.custom_name=iregex:(Cherry Popper)
components.custom_model_data=19
