# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./corrupted_crossbow
model.crossbow_pulling_0=./corrupted_crossbow_pulling_0
model.crossbow_pulling_1=./corrupted_crossbow_pulling_1
model.crossbow_pulling_2=./corrupted_crossbow_pulling_2
model.crossbow_arrow=./corrupted_crossbow_arrow
model.crossbow_firework=./corrupted_crossbow_firework
# components.custom_name=iregex:(Corrupted Crossbow)
components.custom_model_data=22
