# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./crimson_ballista
model.crossbow_pulling_0=./crimson_ballista_pulling_0
model.crossbow_pulling_1=./crimson_ballista_pulling_1
model.crossbow_pulling_2=./crimson_ballista_pulling_2
model.crossbow_arrow=./crimson_ballista_arrow
model.crossbow_firework=./crimson_ballista_firework
# components.custom_name=iregex:(Crimson Ballista)
components.custom_model_data=23
