# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./dark_acorn_acer
model.crossbow_pulling_0=./dark_acorn_acer_pulling_0
model.crossbow_pulling_1=./dark_acorn_acer_pulling_1
model.crossbow_pulling_2=./dark_acorn_acer_pulling_2
model.crossbow_arrow=./dark_acorn_acer_arrow
model.crossbow_firework=./dark_acorn_acer_firework
# components.custom_name=iregex:(Dark Acorn Acer)
components.custom_model_data=26
