# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./dragonsbane_crossbow
model.crossbow_pulling_0=./dragonsbane_crossbow_pulling_0
model.crossbow_pulling_1=./dragonsbane_crossbow_pulling_1
model.crossbow_pulling_2=./dragonsbane_crossbow_pulling_2
model.crossbow_arrow=./dragonsbane_crossbow_arrow
model.crossbow_firework=./dragonsbane_crossbow_firework
# components.custom_name=iregex:(Dragonsbane Crossbow)
components.custom_model_data=30
