# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./echo_shot
model.crossbow_pulling_0=./echo_shot_pulling_0
model.crossbow_pulling_1=./echo_shot_pulling_1
model.crossbow_pulling_2=./echo_shot_pulling_2
model.crossbow_arrow=./echo_shot_arrow
model.crossbow_firework=./echo_shot_firework
# components.custom_name=iregex:(Echo Shot)
components.custom_model_data=32
