# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./ellegaard_crossbow
model.crossbow_pulling_0=./ellegaard_crossbow_pulling_0
model.crossbow_pulling_1=./ellegaard_crossbow_pulling_1
model.crossbow_pulling_2=./ellegaard_crossbow_pulling_2
model.crossbow_arrow=./ellegaard_crossbow_arrow
model.crossbow_firework=./ellegaard_crossbow_firework
# components.custom_name=iregex:(Ellegaard's Crossbow)
components.custom_model_data=34
