# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./ender_dragon_microshot
model.crossbow_pulling_0=./ender_dragon_microshot
model.crossbow_pulling_1=./ender_dragon_microshot_pulling_1
model.crossbow_pulling_2=./ender_dragon_microshot_pulling_2
model.crossbow_arrow=./ender_dragon_microshot_arrow
model.crossbow_firework=./ender_dragon_microshot_firework
# components.custom_name=iregex:(Ender Dragon Microshot)
components.custom_model_data=38
