# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./ender_dragon_microshot_spectral_arrow
components.charged_projectiles=minecraft:spectral_arrow
# components.custom_name=iregex:(Ender Dragon Microshot)
weight=1
components.custom_model_data=38
