# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./ender_destructor
model.crossbow_pulling_0=./ender_destructor_pulling_0
model.crossbow_pulling_1=./ender_destructor_pulling_1
model.crossbow_pulling_2=./ender_destructor_pulling_2
model.crossbow_arrow=./ender_destructor_arrow
model.crossbow_firework=./ender_destructor_firework
# components.custom_name=iregex:(Ender Destructor)
components.custom_model_data=36
