# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./exposed_caver_crossbow
model.crossbow_pulling_0=./exposed_caver_crossbow_pulling_0
model.crossbow_pulling_1=./exposed_caver_crossbow_pulling_1
model.crossbow_pulling_2=./exposed_caver_crossbow_pulling_2
model.crossbow_arrow=./exposed_caver_crossbow_arrow
model.crossbow_firework=./exposed_caver_crossbow_firework
# components.custom_name=iregex:(Caver's Crossbow)
damage=25-49%
components.custom_model_data=16
