# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./firebolt_thrower_quickcharge
model.crossbow_pulling_0=./firebolt_thrower_quickcharge_pulling_0
model.crossbow_pulling_1=./firebolt_thrower_quickcharge_pulling_1
model.crossbow_pulling_2=./firebolt_thrower_quickcharge_pulling_2
model.crossbow_arrow=./firebolt_thrower_quickcharge_arrow
model.crossbow_firework=./firebolt_thrower_quickcharge_firework
# components.custom_name=iregex:(Firebolt Thrower)
enchantments=quick_charge
enchantmentLevels:3-255
weight=2
components.custom_model_data=42
