# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./golden_goliath_ballista
model.crossbow_pulling_0=./golden_goliath_ballista_pulling_0
model.crossbow_pulling_1=./golden_goliath_ballista
model.crossbow_pulling_2=./golden_goliath_ballista_pulling_2
model.crossbow_arrow=./golden_goliath_ballista_arrow
model.crossbow_firework=./golden_goliath_ballista_firework
# components.custom_name=iregex:(Golden Goliath Ballista)
components.custom_model_data=46
