# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./goliath
model.crossbow_pulling_0=./goliath_pulling_0
model.crossbow_pulling_1=./goliath
model.crossbow_pulling_2=./goliath_pulling_2
model.crossbow_arrow=./goliath_arrow
model.crossbow_firework=./goliath_firework
# components.custom_name=iregex:(Goliath)
components.custom_model_data=47
