# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./guardian_microshot
model.crossbow_pulling_0=./guardian_microshot_pulling_0
model.crossbow_pulling_1=./guardian_microshot
model.crossbow_pulling_2=./guardian_microshot_pulling_2
model.crossbow_arrow=./guardian_microshot_arrow
model.crossbow_firework=./guardian_microshot_firework
# components.custom_name=iregex:(Guardian Microshot)
components.custom_model_data=50
