# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/guardian/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/guardian/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./guardian_dragon
model.crossbow_pulling_0=./guardian_dragon_pulling_0
model.crossbow_pulling_1=./guardian_dragon_pulling_1
model.crossbow_pulling_2=./guardian_dragon_pulling_2
model.crossbow_arrow=./guardian_dragon_arrow
model.crossbow_firework=./guardian_dragon_firework
# components.custom_name=iregex:(Guardian Dragon)
components.custom_model_data=49
