# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./imploding_crossbow
model.crossbow_pulling_0=./imploding_crossbow_pulling_0
model.crossbow_pulling_1=./imploding_crossbow_pulling_1
model.crossbow_pulling_2=./imploding_crossbow_pulling_2
model.crossbow_arrow=./imploding_crossbow_arrow
model.crossbow_firework=./imploding_crossbow_firework
# components.custom_name=iregex:(Imploding Crossbow)
components.custom_model_data=55
