# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./lost_signal
model.crossbow_pulling_0=./lost_signal_pulling_0
model.crossbow_pulling_1=./lost_signal_pulling_1
model.crossbow_pulling_2=./lost_signal_pulling_2
model.crossbow_arrow=./lost_signal_arrow
model.crossbow_firework=./lost_signal_firework
# components.custom_name=iregex:(Lost Signal)
components.custom_model_data=60
