# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./mangrove_ballista
model.crossbow_pulling_0=./mangrove_ballista_pulling_0
model.crossbow_pulling_1=./mangrove_ballista_pulling_1
model.crossbow_pulling_2=./mangrove_ballista_pulling_2
model.crossbow_arrow=./mangrove_ballista_arrow
model.crossbow_firework=./mangrove_ballista_firework
# components.custom_name=iregex:(Mangrove Ballista)
components.custom_model_data=62
