# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./oak_ballista
model.crossbow_pulling_0=./oak_ballista_pulling_0
model.crossbow_pulling_1=./oak_ballista_pulling_1
model.crossbow_pulling_2=./oak_ballista_pulling_2
model.crossbow_arrow=./oak_ballista_arrow
model.crossbow_firework=./oak_ballista_firework
# components.custom_name=iregex:(Oak Ballista)
components.custom_model_data=67
