# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./pale_oak_ballista
model.crossbow_pulling_0=./pale_oak_ballista_pulling_0
model.crossbow_pulling_1=./pale_oak_ballista_pulling_1
model.crossbow_pulling_2=./pale_oak_ballista_pulling_2
model.crossbow_arrow=./pale_oak_ballista_arrow
model.crossbow_firework=./pale_oak_ballista_firework
# components.custom_name=iregex:(Pale Oak Ballista)
components.custom_model_data=68
