# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./pride_of_the_piglins
model.crossbow_pulling_0=./pride_of_the_piglins_pulling_0
model.crossbow_pulling_1=./pride_of_the_piglins_pulling_1
model.crossbow_pulling_2=./pride_of_the_piglins_pulling_2
model.crossbow_arrow=./pride_of_the_piglins_arrow
model.crossbow_firework=./pride_of_the_piglins_firework
# components.custom_name=iregex:(Pride of the Piglins)
components.custom_model_data=71
