# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./propagun
model.crossbow_pulling_0=./propagun_pulling_0
model.crossbow_pulling_1=./propagun_pulling_1
model.crossbow_pulling_2=./propagun_pulling_2
model.crossbow_arrow=./propagun_arrow
model.crossbow_firework=./propagun_firework
# components.custom_name=iregex:(Propagun)
components.custom_model_data=72
