# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./ravaged_experiment
model.crossbow_pulling_0=./ravaged_experiment_pulling_0
model.crossbow_pulling_1=./ravaged_experiment_pulling_1
model.crossbow_pulling_2=./ravaged_experiment_pulling_2
model.crossbow_arrow=./ravaged_experiment_arrow
model.crossbow_firework=./ravaged_experiment_firework
# components.custom_name=iregex:(Ravaged Experiment)
components.custom_model_data=75
