# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./sdmg
model.crossbow_pulling_0=./sdmg_pulling_1
model.crossbow_pulling_1=./sdmg_pulling_0
model.crossbow_pulling_2=./sdmg_pulling_1
model.crossbow_arrow=./sdmg_arrow
model.crossbow_firework=./sdmg_firework
# components.custom_name=iregex:(S.D.M.G.)
components.custom_model_data=80
