# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./slayer_dragon
model.crossbow_pulling_0=./slayer_dragon_pulling_0
model.crossbow_pulling_1=./slayer_dragon_pulling_1
model.crossbow_pulling_2=./slayer_dragon_pulling_2
model.crossbow_arrow=./slayer_dragon_arrow
model.crossbow_firework=./slayer_dragon_firework
# components.custom_name=iregex:(Slayer of Dragons)
components.custom_model_data=84
