# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./spruce_cone_slinger
model.crossbow_pulling_0=./spruce_cone_slinger_pulling_0
model.crossbow_pulling_1=./spruce_cone_slinger_pulling_1
model.crossbow_pulling_2=./spruce_cone_slinger_pulling_2
model.crossbow_arrow=./spruce_cone_slinger_arrow
model.crossbow_firework=./spruce_cone_slinger_firework
# components.custom_name=iregex:(Spruce Cone Slinger)
components.custom_model_data=90
