# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./teleportation_crossbow_quickcharge
model.crossbow_pulling_0=./teleportation_crossbow_quickcharge_pulling_0
model.crossbow_pulling_1=./teleportation_crossbow_quickcharge_pulling_1
model.crossbow_pulling_2=./teleportation_crossbow_quickcharge_pulling_2
model.crossbow_arrow=./teleportation_crossbow_quickcharge_arrow
model.crossbow_firework=./teleportation_crossbow_quickcharge_firework
# components.custom_name=iregex:(Teleportation Crossbow)
enchantments=quick_charge
enchantmentLevels:3-255
weight=2
components.custom_model_data=91
