# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./the_first_dragon
model.crossbow_pulling_0=./the_first_dragon_pulling_0
model.crossbow_pulling_1=./the_first_dragon_pulling_1
model.crossbow_pulling_2=./the_first_dragon_pulling_2
model.crossbow_arrow=./the_first_dragon_arrow
model.crossbow_firework=./the_first_dragon_firework
# components.custom_name=iregex:(The First Dragon)
components.custom_model_data=92
