# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./twisted_thrower
model.crossbow_pulling_0=./twisted_thrower_pulling_0
model.crossbow_pulling_1=./twisted_thrower_pulling_1
model.crossbow_pulling_2=./twisted_thrower_pulling_2
model.crossbow_arrow=./twisted_thrower_arrow
model.crossbow_firework=./twisted_thrower_firework
# components.custom_name=iregex:(Twisted Thrower)
components.custom_model_data=96
