# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:crossbow
model=./weeping_wrangler
model.crossbow_pulling_0=./weeping_wrangler_pulling_0
model.crossbow_pulling_1=./weeping_wrangler_pulling_1
model.crossbow_pulling_2=./weeping_wrangler_pulling_2
model.crossbow_arrow=./weeping_wrangler_arrow
model.crossbow_firework=./weeping_wrangler_firework
# components.custom_name=iregex:(Weeping Wrangler)
components.custom_model_data=101
