# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=armor
matchItems=chainmail_chestplate
texture.chainmail_layer_1=combat_layer_1
# components.custom_name=iregex:(combat chestplate)
damage=0-24%
components.custom_model_data=3
