# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=armor
matchItems=chainmail_boots
texture.chainmail_layer_1=exposed_trial_layer_1
# components.custom_name=iregex:(trial boots)
damage=25-49%
components.custom_model_data=11
