# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=armor
matchItems=chainmail_leggings
texture.chainmail_layer_2=phantom_layer_2
# components.custom_name=iregex:(phantom leggings)
components.custom_model_data=27
