# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=armor
matchItems=chainmail_helmet
texture.chainmail_layer_1=weathered_combat_layer_1
# components.custom_name=iregex:(combat helmet)
damage=50-74%
components.custom_model_data=3
