# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=ctm_compact
matchTiles=mushroom_block_inside
tiles=0 textures/block/mushroom_block_inside 2-4
innerSeams=true