# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=dark_prismarine dark_prismarine_slab dark_prismarine_stairs
method=random
tiles=textures/block/dark_prismarine.png 0-5
biomes=warm_ocean lukewarm_ocean deep_lukewarm_ocean ocean deep_ocean cold_ocean deep_cold_ocean frozen_ocean deep_frozen_ocean
weights=7 1 1 1 1 1 1
maxHeight=62
symmetry=all