# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=red_sandstone
faces=sides
method=ctm_compact
tiles=textures/block/red_sandstone.png textures/block/red_sandstone_bottom.png textures/block/red_sandstone_bottom.png textures/block/red_sandstone.png 4