# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=lime_stained_glass
connect=block
method=ctm
tiles=0-11 16-27 32-43 48-58
biomes=barely_default:nostalgia_hills