# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=22
nbt.1.ArmorItems.3.id=minecraft:wither_rose
biomes.1=nether_wastes crimson_forest warped_forest soul_sand_valley basalt_deltas

skins.2=21
nbt.2.ArmorItems.3.id=minecraft:wither_rose

skins.3=1
nbt.3.ArmorItems.3.id=minecraft:black_dye

skins.4=2
nbt.4.ArmorItems.3.id=minecraft:blue_dye

skins.5=3
nbt.5.ArmorItems.3.id=minecraft:brown_dye

skins.6=4
nbt.6.ArmorItems.3.id=minecraft:cyan_dye

skins.7=5
nbt.7.ArmorItems.3.id=minecraft:gray_dye

skins.8=6
nbt.8.ArmorItems.3.id=minecraft:green_dye

skins.9=7
nbt.9.ArmorItems.3.id=minecraft:light_blue_dye

skins.10=8
nbt.10.ArmorItems.3.id=minecraft:light_gray_dye

skins.11=9
nbt.11.ArmorItems.3.id=minecraft:lime_dye

skins.12=10
nbt.12.ArmorItems.3.id=minecraft:magenta_dye

skins.13=11
nbt.13.ArmorItems.3.id=minecraft:orange_dye

skins.14=12
nbt.14.ArmorItems.3.id=minecraft:pink_dye

skins.15=13
nbt.15.ArmorItems.3.id=minecraft:purple_dye

skins.16=14
nbt.16.ArmorItems.3.id=minecraft:red_dye

skins.17=15
nbt.17.ArmorItems.3.id=minecraft:white_dye

skins.18=16
nbt.18.ArmorItems.3.id=minecraft:yellow_dye

skins.19=17
nbt.19.ArmorItems.3.id=minecraft:chorus_flower

skins.20=18
nbt.20.ArmorItems.3.id=minecraft:torchflower

skins.21=19
nbt.21.ArmorItems.3.id=minecraft:pitcher_pod

skins.22=20
nbt.22.ArmorItems.3.id=minecraft:open_eyeblossom

skins.23=23
nbt.23.ArmorItems.3.id=minecraft:sculk_shrieker