# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=4
nbt.1.ArmorItems.3.id=minecraft:red_mushroom

skins.2=4
nbt.2.ArmorItems.3.id=minecraft:brown_mushroom

skins.3=4
name.3=iregex:(Cluckshroom)

skins.4=2
biomes.4=mangrove_swamp savanna savanna_plateau windswept_savanna dark_forest

skins.5=3
biomes.5=jungle sparse_jungle bamboo_jungle flower_forest

skins.6=1