# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=4
health.1=0-25%

skins.2=3
health.2=26-50%

skins.3=2
health.3=51-75%

skins.4=1
health.4=76-100%