# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=cherry_log_horizontal
method=horizontal
tiles=0 textures/block/cherry_log.png 2 textures/block/cherry_log_horizontal.png