# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=4
sizes.1=0
nbt.1.ArmorItems.3.id=minecraft:tropical_fish

skins.2=5
sizes.2=1
nbt.2.ArmorItems.3.id=minecraft:tropical_fish

skins.3=5
sizes.3=3
nbt.3.ArmorItems.3.id=minecraft:tropical_fish

skins.4=6
nbt.4.ArmorItems.3.id=minecraft:cauldron

skins.5=8
sizes.5=0
nbt.5.ArmorItems.3.id=minecraft:glass_bottle

skins.6=9
sizes.6=1
nbt.6.ArmorItems.3.id=minecraft:glass_bottle

skins.7=6
name.7=ipattern:*Spud

skins.8=7
nbt.8.ArmorItems.3.id=minecraft:pink_dye

skins.9=4
sizes.9=0
name.9=ipattern:Tropical*

skins.10=5
sizes.10=1
name.10=ipattern:Tropical*

skins.11=5
sizes.11=3
name.11=ipattern:Tropical*

skins.12=1
sizes.12=0

skins.13=2
sizes.13=1

skins.14=3
sizes.14=3