# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=netherrack crimson_nylium blackstone nether_gold_ore nether_quartz_ore soul_sand soul_soil
connectBlocks=nether_wart_block
connect=block
method=overlay
tiles=<skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> 4 <skip>
biomes=crimson_forest