# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/sky.properties
source=./sky1.png
startFadeIn=17\:50
endFadeIn=18\:38
blend=add
rotate=true
startFadeOut=05\:12
endFadeOut=06\:00
heights=50-256
transition=10