# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/sky.properties
source=./sky2.png
startFadeIn=18\:47
endFadeIn=19\:42
blend=add
rotate=true
startFadeOut=04\:12
endFadeOut=05\:01
heights=50-256
transition=10