# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/sky.properties
source=./sky3.png
startFadeIn=19\:48
endFadeIn=00\:00
blend=add
rotate=true
endFadeOut=04\:12
heights=50-256
transition=10