# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=minecraft:podzol
method=overlay
tiles=<skip> <skip> <skip> <skip> <skip> <skip> <skip> 7 <skip> 9 <skip> <skip> <skip> <skip> <skip> <skip> <skip>
connect=block
connectTiles=grass_block_side
faces=sides
weight=2