# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=4
biomes.1=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean barely_default:ice_desert
heights.1=320-52

skins.2=5-7
heights.2=(-1)-(-63)

skins.3=1-3