# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=2
biomes.1=snowy_beach frozen_ocean deep_frozen_ocean

skins.2=3
biomes.2=mangrove_swamp swamp

skins.3=1