# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=random
matchTiles=soul_sand.png
tiles=textures/block/soul_sand.png 0-2
biomes=soul_sand_valley
weights=297 1 1 1