# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=light_blue_stained_glass_pane
connect=block
method=ctm
faces=sides
tiles=0-11 16-27 32-43 48-58
biomes=barely_default:nostalgia_hills