# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=4
nbt.1.ArmorItems.3.id=minecraft:dandelion
health.1=0-10%

models.2=4
nbt.2.ArmorItems.3.id=minecraft:azure_bluet
health.2=0-10%

models.3=4
nbt.3.ArmorItems.3.id=minecraft:poppy
health.3=0-10%

models.4=4
nbt.4.ArmorItems.3.id=minecraft:allium
health.4=0-10%

models.5=4
nbt.5.ArmorItems.3.id=minecraft:oxeye_daisy
health.5=0-10%

models.6=4
nbt.6.ArmorItems.3.id=minecraft:cornflower
health.6=0-10%

models.7=4
nbt.7.ArmorItems.3.id=minecraft:pink_tulip
health.7=0-10%

models.8=4
nbt.8.ArmorItems.3.id=minecraft:white_tulip
health.8=0-10%

models.9=4
nbt.9.ArmorItems.3.id=minecraft:red_tulip
health.9=0-10%

models.10=4
nbt.10.ArmorItems.3.id=minecraft:orange_tulip
health.10=0-10%

models.11=3
nbt.11.ArmorItems.3.id=minecraft:dandelion

models.12=3
nbt.12.ArmorItems.3.id=minecraft:azure_bluet

models.13=3
nbt.13.ArmorItems.3.id=minecraft:poppy

models.14=3
nbt.14.ArmorItems.3.id=minecraft:allium

models.15=3
nbt.15.ArmorItems.3.id=minecraft:oxeye_daisy

models.16=3
nbt.16.ArmorItems.3.id=minecraft:cornflower

models.17=3
nbt.17.ArmorItems.3.id=minecraft:pink_tulip

models.18=3
nbt.18.ArmorItems.3.id=minecraft:white_tulip

models.19=3
nbt.19.ArmorItems.3.id=minecraft:red_tulip

models.20=3
nbt.20.ArmorItems.3.id=minecraft:orange_tulip

models.21=4
name.21=iregex:(Moobloom)
health.21=0-10%

models.23=4
name.23=iregex:(Moolip)
health.23=0-10%

models.24=3
name.24=iregex:(Moobloom)

models.25=3
name.25=iregex:(Moolip)

models.26=4
health.26=0-10%
biomes.26=flower_forest

models.27=3
biomes.27=flower_forest

models.28=2
health.28=0-10%

models.29=1