# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=nether_bricks
method=random
tiles=textures/block/nether_bricks warped_nether_bricks_0
biomes=warped_forest
weights=19 1
symmetry=all