# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=nether_bricks_1
method=random
tiles=textures/block/nether_bricks_1 warped_nether_bricks_1
biomes=warped_forest
weights=19 1
symmetry=all