# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:mace
texture=./comet_on_a_stick
model=./comet_on_a_stick
# components.custom_name=iregex:(Comet on a Stick)
components.custom_model_data=13
