# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:mace
texture=portal_buster_mace
model=portal_buster_mace
# components.custom_name=iregex:(Portal Buster Mace)
weight=2
components.custom_model_data=41
