# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:mace
texture=stormlander
model=stormlander_lightning
# components.custom_name=iregex:(Stormlander)
enchantments=breach smite bane_of_arthropods
enchantmentLevels:4-255
weight=1
components.custom_model_data=55
