# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=red_sandstone_end.png
matchBlocks=minecraft:cut_red_sandstone
method=ctm_compact
tiles=textures/block/red_sandstone_end.png textures/block/red_sandstone_top.png optifine/ctm/red_sandstone/top/2 optifine/ctm/red_sandstone/top/3 optifine/ctm/red_sandstone/top/4