# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=armor
matchItems=iron_boots
texture.iron_layer_1=spelunker_layer_1
# components.custom_name=iregex:(spelunker's boots)
components.custom_model_data=31
