# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=birch_log_horizontal
method=horizontal
tiles=0 textures/block/birch_log.png 2 textures/block/birch_log_horizontal.png