# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:shield
model=./golden_goliath_shield
model.shield_blocking=./golden_goliath_shield_blocking
# components.custom_name=iregex:(Golden Goliath Shield)
components.custom_model_data=14
