# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:shield
model=./mushroom_guy
model.shield_blocking=./mushroom_guy_blocking
# components.custom_name=iregex:(Mushroom Guy)
components.custom_model_data=19
