# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:shield
model=./nameless_shield
model.shield_blocking=./nameless_shield_blocking
# components.custom_name=iregex:(Nameless Shield)
components.custom_model_data=20
