# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:shield
model=./vanguard_shield
model.shield_blocking=./vanguard_shield_blocking
# components.custom_name=iregex:(vanguard shield)
components.custom_model_data=36
