# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
model=./ruby_turtle_shelmet
matchItems=turtle_helmet
# components.custom_name=iregex:(ruby turtle shelmet)
components.custom_model_data=1
