# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=1-11 13-14 16-26
weights.1=32 2 2 2 2 2 2 2 2 2 32 1 2 1 1 1 1 1 1 1 1 1 1 1
biomes.1=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean

skins.2=1-10 12-14 16-26
weights.2=32 2 2 2 2 2 2 2 2 2 32 1 2 1 1 1 1 1 1 1 1 1 1 1
biomes.2=swamp mangrove_swamp jungle sparse_jungle bamboo_jungle

skins.3=1-10 13-26
weights.3=32 2 2 2 2 2 2 2 2 2 1 2 16 1 1 1 1 1 1 1 1 1 1 1
biomes.3=desert

skins.4=1-10 13-14 16-26
weights.4=64 2 2 2 2 2 2 2 2 2 1 2 1 1 1 1 1 1 1 1 1 1 1