# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=seagrass.png
tiles=./creeper_plants_bottom
biomes=taiga barely_default:creeper_woods
heights=62