# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=seagrass_custom
tiles=./reeds_top
biomes=river swamp old_growth_pine_taiga old_growth_spruce_taiga barely_default:soggy_swamp
heights=62