# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=random
matchTiles=minecraft:tall_seagrass_top
tiles=./tall_sculk_seagrass_top
weights=1
biomes=deep_dark
linked=true