# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=random
matchTiles=minecraft:tall_seagrass_bottom
tiles=./tall_sculk_seagrass_bottom
weights=1
biomes=deep_dark
linked=true