# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=vertical
matchTiles=textures/block/cactus_side
matchBlocks=minecraft:cactus
tiles=textures/block/cactus_side.png textures/block/cactus_side.png textures/block/cactus_end.png textures/block/cactus_end.png
weight=1