type=item
matchItems=crossbow
model=./crimson_grimoire_closed
model.crossbow_pulling_0=crimson_grimoire_partial
model.crossbow_pulling_1=crimson_grimoire_partial2
model.crossbow_pulling_2=crimson_grimoire3
model.crossbow_arrow=crimson_grimoire2
model.crossbow_firework=crimson_grimoire2
# components.custom_name=ipattern:*Grimoire Braisé
components.custom_model_data=105