# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=vertical
faces=sides
matchBlocks=minecraft:sugar_cane
tiles=0 textures/block/sugar_cane.png textures/block/sugar_cane.png 0