# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=2
nbt.1.ArmorItems.3.id=minecraft:dirt

models.2=3
nbt.2.ArmorItems.3.id=minecraft:grass_block

models.3=2
nbt.3.ArmorItems.3.id=minecraft:sand

models.4=1