# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
matchItems=minecraft:stone_sword
model=optifine/cit/item/dancers_sword
texture=dancers_sword
# components.custom_name=ipattern:*Dancer's Sword
components.custom_model_data=10
