# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=ctm_compact
matchTiles=glow_lichen.png
tiles=0-3 1
biomes=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean
weight=1