# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=7
biomes.1=mushroom_fields

skins.2=6
biomes.2=nether_wastes crimson_forest warped_forest soul_sand_valley basalt_deltas

skins.3=14
biomes.3=the_end end_highlands end_midlands small_end_islands end_barrens

skins.4=2 9-11
heights.4=60-0
weights.4=100 20 20 20

skins.5=8 12 13
biomes.5=deep_dark

skins.6=8 12
heights.6=(-1)-(-64)
weights.6=100 30

skins.7=3 16
biomes.7=desert
weights.7=64 1

skins.8=4
biomes.8=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean

skins.9=5 16
biomes.9=badlands eroded_badlands wooded_badlands
weights.9=64 1

skins.10=1 15 17
biomes.10=barely_default:pumpkin_pastures
weights.10=512 1 64

skins.11=3 4
biomes.11=barely_default:ice_desert

skins.11=1 15
heights.12=320-0
weights.12=128 1