# See https://GitHub.com/sp513x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=1
colors.1=white

skins.2=2
colors.2=light_gray

skins.3=3
colors.3=gray

skins.4=4
colors.4=black

skins.5=5
colors.5=brown

skins.6=6
colors.6=red

skins.7=7
colors.7=orange

skins.8=8
colors.8=yellow

skins.9=9
colors.9=lime

skins.10=10
colors.10=green

skins.11=11
colors.11=cyan

skins.12=12
colors.12=light_blue

skins.13=13
colors.13=blue

skins.14=14
colors.14=purple

skins.15=15
colors.15=magenta

skins.16=16
colors.16=pink