# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=15
biomes.1=desert savanna savanna_plateau windswept_savanna badlands eroded_badlands wooded_badlands barely_default:ice_desert
health.1=0-10%

skins.2=14
biomes.2=desert savanna savanna_plateau windswept_savanna badlands eroded_badlands wooded_badlands barely_default:ice_desert

skins.3=13
biomes.3=swamp mangrove_swamp jungle sparse_jungle bamboo_jungle
health.3=0-10%

skins.4=12
biomes.4=swamp mangrove_swamp jungle sparse_jungle bamboo_jungle

skins.5=11
biomes.5=birch_forest old_growth_birch_forest
health.5=0-10%

skins.6=10
biomes.6=birch_forest old_growth_birch_forest

skins.7=9
biomes.7=stony_shore stony_peaks old_growth_pine_taiga old_growth_spruce_taiga
health.7=0-10%

skins.8=8
biomes.8=stony_shore stony_peaks old_growth_pine_taiga old_growth_spruce_taiga

skins.9=7
biomes.9=plains sunflower_plains barely_default:nostalgia_hills
health.9=0-10%

skins.10=6
biomes.10=plains sunflower_plains barely_default:nostalgia_hills

skins.11=5
biomes.11=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean
health.11=0-10%

skins.12=4
health.12=0-10%

skins.13=3
biomes.13=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean

skins.14=2