# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=2-3
biomes.1=stony_shore stony_peaks old_growth_pine_taiga old_growth_spruce_taiga

skins.2=4
biomes.2=swamp mangrove_swamp jungle sparse_jungle bamboo_jungle

skins.3=2