# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
model=./cyklopps_helmet
matchItems=netherite_helmet
# components.custom_name=iregex:(CYKLOPPS' helmet)
components.custom_model_data=22
