# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
model=./mega_x_chestplate_fire_protection
matchItems=netherite_chestplate
# components.custom_name=iregex:(mega x chestplate)
enchantments=fire_protection
weight=1
components.custom_model_data=63
