# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=item
model=./mega_x_boots_protection
matchItems=netherite_boots
# components.custom_name=iregex:(mega x boots)
enchantments=protection fire_protection blast_protection projectile_protection
enchantmentLevels:4-255
weight=2
components.custom_model_data=62
