# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=ctm_compact
matchTiles=acacia_leaves.png
tiles=0 textures/block/acacia_leaves.png textures/block/acacia_leaves.png textures/block/acacia_leaves.png textures/block/acacia_leaves.png