# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
faces=all
matchTiles=acacia_fence acacia_button
tiles=./acacia_planks
biomes=barely_default:nostalgia_hills
weight=2