# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=textures/block/birch_log_horizontal textures/block/birch_log_vertical birch_log
tiles=./birch_log
biomes=barely_default:nostalgia_hills
weight=2