# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=vertical
matchTiles=textures/block/cactus_side
matchBlocks=minecraft:cactus
tiles=./cactus_side ./cactus_side ./cactus_end ./cactus_end
biomes=barely_default:nostalgia_hills
weight=2