# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
faces=all
matchTiles=cherry_fence cherry_button
tiles=./cherry_planks
biomes=barely_default:nostalgia_hills
weight=2