# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=chiseled_quartz_block_top
tiles=./chiseled_quartz_block_top
biomes=barely_default:nostalgia_hills