# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=textures/block/cobblestone textures/block/cobblestone_1 textures/block/cobblestone_2 textures/block/cobblestone_3 textures/block/cobblestone_4
tiles=./cobblestone
biomes=barely_default:nostalgia_hills