# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=crafting_table_side crafting_table_front
tiles=./crafting_table_side
biomes=barely_default:nostalgia_hills