# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=textures/block/dark_oak_log_horizontal textures/block/dark_oak_log_vertical dark_oak_log
tiles=./dark_oak_log
biomes=barely_default:nostalgia_hills
weight=2