# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=vertical
faces=sides
matchBlocks=minecraft:diamond_block
tiles=./diamond_block_side ./diamond_block ./diamond_block ./diamond_block_side
biomes=barely_default:nostalgia_hills
weight=2