# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
faces=top
matchBlocks=minecraft:diamond_block
tiles=./diamond_block
biomes=barely_default:nostalgia_hills
weight=2