# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=dirt farmland_front farmland_side farmland_getting_there_0_front farmland_getting_there_1_front farmland_getting_there_2_front farmland_getting_there_3_front farmland_getting_there_4_front farmland_getting_there_5_front farmland_getting_there_0_side farmland_getting_there_1_side farmland_getting_there_2_side farmland_getting_there_3_side farmland_getting_there_4_side farmland_getting_there_5_side
tiles=./dirt
biomes=barely_default:nostalgia_hills