# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=dirt_path_top better_grass_path_side
tiles=./dirt_path_top
biomes=barely_default:nostalgia_hills