# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=dispenser_front_vertical
tiles=./dispenser_front_vertical
biomes=barely_default:nostalgia_hills