# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
faces=top
matchBlocks=minecraft:gold_block light_weighted_pressure_plate
tiles=./gold_block
biomes=barely_default:nostalgia_hills
weight=2