# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=vertical
faces=sides
matchBlocks=gold_block light_weighted_pressure_plate
tiles=./gold_block_side ./gold_block ./gold_block ./gold_block_side
biomes=barely_default:nostalgia_hills
weight=2