# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=grass_block_snow better_snow_grass_side
tiles=./grass_block_snow
biomes=barely_default:nostalgia_hills