# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=grass_block_side_overlay better_grass_side
tiles=./grass_block_side_overlay
biomes=barely_default:nostalgia_hills