# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=vertical
faces=sides
matchBlocks=iron_block heavy_weighted_pressure_plate
tiles=./iron_block_side ./iron_block ./iron_block ./iron_block_side
biomes=barely_default:nostalgia_hills
weight=2