# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
faces=bottom
matchBlocks=minecraft:iron_block heavy_weighted_pressure_plate
tiles=./iron_block_bottom
biomes=barely_default:nostalgia_hills
weight=2