# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=textures/block/jungle_log_horizontal textures/block/jungle_log_vertical jungle_log
tiles=./jungle_log
biomes=barely_default:nostalgia_hills
weight=2