# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=mossy_stone_bricks mossy_stone_bricks_1 mossy_stone_bricks_2
tiles=./mossy_stone_bricks
biomes=barely_default:nostalgia_hills