# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=textures/block/mossy_cobblestone textures/block/mossy_cobblestone_0 textures/block/mossy_cobblestone_1 textures/block/mossy_cobblestone_2 textures/block/mossy_cobblestone_3 textures/block/mossy_cobblestone_4
tiles=./mossy_cobblestone
biomes=barely_default:nostalgia_hills