# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=mycelium_side mycelium_side_snow better_mycelium_side
tiles=./mycelium_side
biomes=barely_default:nostalgia_hills