# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=textures/block/oak_log_horizontal textures/block/oak_log_vertical oak_log
tiles=./oak_log
biomes=barely_default:nostalgia_hills
weight=2