# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
faces=all
matchTiles=oak_fence oak_button crafting_table_bottom
tiles=./oak_planks
biomes=barely_default:nostalgia_hills
weight=2