# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=observer_front observer_front_on
tiles=./observer_front
biomes=barely_default:nostalgia_hills