# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=oxeye_daisy oxeye_daisy_1 oxeye_daisy_2 oxeye_daisy_3
tiles=./oxeye_daisy
biomes=barely_default:nostalgia_hills