# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=piston_bottom dispenser_bottom dispenser_top dispenser_side_vertical dropper_bottom dropper_top dropper_side_vertical
tiles=./piston_bottom
biomes=barely_default:nostalgia_hills