# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=prismarine_bricks prismarine_bricks_top
tiles=./prismarine_bricks
biomes=barely_default:nostalgia_hills