# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=quartz_pillar_horizontal quartz_pillar_vertical
tiles=./quartz_pillar
biomes=barely_default:nostalgia_hills