# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=red_sandstone_top chiseled_red_sandstone_end red_sandstone_end chiseled_red_sandstone_end
tiles=./red_sandstone_top
biomes=barely_default:nostalgia_hills