# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=sandstone_top chiseled_sandstone_end chiseled_sandstone_end_0 chiseled_sandstone_end sandstone_end
tiles=./sandstone_top
biomes=barely_default:nostalgia_hills