# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=textures/block/spruce_log_horizontal textures/block/spruce_log_vertical spruce_log
tiles=./spruce_log
biomes=barely_default:nostalgia_hills
weight=2