# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=warped_planks
method=overlay_random
tiles=<skip> crimson_nylium_overlay
biomes=crimson_forest
weights=4 1
symmetry=all