# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=oak_planks spruce_planks birch_planks jungle_planks dark_oak_planks mangrove_planks acacia_planks
method=overlay_random
tiles=<skip> mossy_overlay
biomes=warm_ocean lukewarm_ocean deep_lukewarm_ocean ocean deep_ocean cold_ocean deep_cold_ocean frozen_ocean deep_frozen_ocean lush_caves mangrove_swamp jungle
weights=4 1
maxHeight=62
symmetry=all