# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=crimson_planks
method=overlay_random
tiles=<skip> warped_nylium_overlay
biomes=warped_forest
weights=4 1
symmetry=all