# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=6
nbt.1.ArmorItems.3.id=minecraft:chest
health.1=0-10%

models.2=5
nbt.2.ArmorItems.3.id=minecraft:chest

models.3=4
name.3=iregex:(Technoblade)
health.3=0-10%

models.4=3
name.4=iregex:(Technoblade)

models.5=6
name.5=ipattern:*Bank
health.5=0-10%

models.6=5
name.6=ipattern:*Bank

models.7=2
health.7=0-10%

models.8=1