# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=4
biomes.1=grove frozen_ocean deep_frozen_ocean frozen_river snowy_beach snowy_taiga ice_spikes old_growth_spruce_taiga old_growth_pine_taiga
name.1=iregex:(Technoblade)

models.2=3
name.2=iregex:(Technoblade)

models.3=2
biomes.3=grove frozen_ocean deep_frozen_ocean frozen_river snowy_beach snowy_taiga ice_spikes old_growth_spruce_taiga old_growth_pine_taiga

models.4=1