# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=2
name.1=iregex:Kirin.*

models.2=2
name.2=iregex:Girin.*

models.3=2
name.3=iregex:Qillin.*

models.4=3
name.4=ipattern:Skeleton*
baby.4=false

models.5=1-2
weights.5=128 1