# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=6
name.1=iregex:(Reuben)
health.1=0-10%

skins.2=4
biomes.2=grove frozen_ocean deep_frozen_ocean frozen_river snowy_beach snowy_taiga ice_spikes
health.2=0-10%

skins.3=5
name.3=iregex:(Reuben)

skins,4=3
biomes.4=grove frozen_ocean deep_frozen_ocean frozen_river snowy_beach snowy_taiga ice_spikes

skins.5=8
biomes.5=dark_forest
health.5=0-10%

skins.6=7
biomes.6=dark_forest

skins.7=10
biomes.7=old_growth_spruce_taiga old_growth_pine_taiga
health.7=0-10%

skins.8=9
biomes.8=old_growth_spruce_taiga old_growth_pine_taiga

skins.9=12
biomes.9=snowy_plains
health.9=0-10%

skins.10=11
biomes.10=snowy_plains

skins.11=14
biomes.11=desert badlands eroded_badlands wooded_badlands
health.11=0-10%

skins.12=13
biomes.12=desert badlands eroded_badlands wooded_badlands

skins.13=16
biomes.13=jungle sparse_jungle bamboo_jungle
health.13=0-10%

skins.14=15
biomes.14=jungle sparse_jungle bamboo_jungle

skins.15=18
biomes.15=soul_sand_valley nether_wastes crimson_forest warped_forest basalt_deltas
health.15=0-10%

skins.16=17
biomes.16=soul_sand_valley nether_wastes crimson_forest warped_forest basalt_deltas

skins.17=2
health.17=0-10%

skins.18=1