# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
skins.1=9
name.1=iregex:(Reuben)

skins.2=8
biomes.2=frozen_ocean deep_frozen_ocean frozen_river snowy_beach snowy_taiga ice_spikes barely_default:ice_desert

skins.3=1-7
biomes.3=swamp
weights.3=50 45 2 2 2 1 1

skins.4=1 10-15
biomes.4=mangrove_swamp barely_default:soggy_swamp
weights.4=50 45 2 2 2 1 1

skins.5=16
biomes.5=dark_forest pale_garden

skins.6=18 19
biomes.6=snowy_plains

skins.7=20
biomes.7=desert badlands eroded_badlands wooded_badlands barely_default:crown_mesa

skins.8=21
biomes.8=jungle sparse_jungle bamboo_jungle

skins.9=17
biomes.9=old_growth_spruce_taiga old_growth_pine_taiga

skins.10=22
biomes.10=soul_sand_valley nether_wastes crimson_forest warped_forest basalt_deltas

skins.11=1