# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=textures/block/oak_log_vertical
method=horizontal
tiles=0 textures/block/oak_log.png 2 textures/block/oak_log_vertical.png
weight=1