# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=armor
matchItems=diamond_helmet
texture.diamond_layer_1=ar_useful_layer_1
# components.custom_name=iregex:(ar helmet)
damage=80-100%
weight=1
components.custom_model_data=1
