# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=elytra
matchItems=minecraft:elytra
texture=broken_block_elytra
# components.custom_name=iregex:(The Fourth Block)
components.damage=431
weight=1
components.custom_model_data=13
