# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=elytra
matchItems=minecraft:elytra
texture=dark_dragon_wings
# components.custom_name=iregex:(Dark Dragon Wings)
components.custom_model_data=19
