# By Mickey Joe Alpha - https://www.YouTube.com/@MushirMickeyJoe

# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit.properties
# and https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/cit_single.properties
type=elytra
matchItems=minecraft:elytra
texture=demiflux_pride_elytra
# components.custom_name=iregex:(Demiflux Pride Elytra)
components.custom_model_data=21
