# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=1-15
biomes.1=savanna savanna_plateau badlands eroded_badlands windswept_savanna wooded_badlands mangrove_swamp
weights.1=32 32 32 1 1 1 32 32 32 32 32 32 32 32 32

models.2=1-18
weights.2=32 32 32 1 1 1 32 32 32 32 32 32 32 32 32 32 32 32