# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=dirt podzol rooted_dirt coarse_dirt
method=overlay
tiles=0-16
connect=block
connectTiles=grass_block_top
tintIndex=1
tintBlock=minecraft:grass_block
faces=top
weight=2