# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=12
name.1=ipattern:*Ocelot

models.2=7
name.2=ipattern:*Panda

models.3=6
name.3=ipattern:*Fox

models.4=8
name.4=ipattern:*Polar Bear

models.5=9
name.5=ipattern:*Pufferfish

models.6=5
name.6=ipattern:*Bee

models.7=4
name.7=ipattern:*Cow

models.8=10 11
name.8=ipattern:*Kiosk
weights.8=4 1

models.9=14
name.9=ipattern:Arch*

models.10=3-12
name.10=ipattern:*NPC
weights.10=48 1 1 1 1 1 1 4 1 1 

models.11=3
name.11=ipattern:*Scientist

models.12=16
name.12=ipattern:*Tumbler

models.13=13
name.13=ipattern:*Glider

models.14=15
name.14=ipattern:*Brawler

models.15=2
name.15=ipattern:*Retired Adventurer

models.16=2-16
professions.16=minecraft:nitwit
weights.16=48 1 1 1 1 1 1 4 1 1 1 1 1 1 1

models.17=1