# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=4
nbt.1.ArmorItems.2.id=minecraft:rabbit_stew

models.2=3
name.2=iregex:(The Unshorn)

models.3=1 5 3 6
weights.3=128 256 1 1
weather.3=rain
minHeight.3=60
biomes.3=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean barely_default:ice_desert
nbt.3.ArmorItems.2.id=exists:false

models.4=1 5 3 6
weights.4=128 256 1 1
weather.4=rain
minHeight.4=60
biomes.4=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean barely_default:ice_desert
nbt.4.ArmorItems.3.id=exists:false


models.5=1-3 6
weights.5=128 256 1 1
minHeight.5=60

models.6=1-2 6
weights.6=128 256 1