# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchBlocks=warped_wart_block
method=overlay
tiles=<skip> 1 <skip> 3-13 <skip> 15 <skip>
connectTiles=shroomlight
biomes=warped_forest nether_wastes soul_sand_valley crimson_forest basalt_deltas