# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
method=fixed
matchTiles=cyan_glazed_terracotta
tiles=./crown_mesa_cyan_glazed_terracotta
biomes=barely_default:crown_mesa