# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/ctm.properties
matchTiles=basalt_side
method=vertical
tiles=optifine/ctm/basalt_v/0 textures/block/basalt_side.png optifine/ctm/basalt_v/2 textures/block/basalt_ends