# See https://GitHub.com/sp614x/OptiFine/blob/master/OptiFineDoc/doc/random_entities.properties
models.1=3
nbt.1.ArmorItems.3.id=minecraft:cauldron

models.2=1
nbt.2.ArmorItems.3.id=minecraft:glass_bottle

models.3=2
name.3=ipattern:*Spud

models.4=1